alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
domains:
- domain: golem.1fpga.cloud
  type: PRIMARY
  zone: 1fpga.cloud
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: golem-1fpga-cloud
    match:
      path:
        prefix: /
name: golem-1fpga-cloud
region: nyc
static_sites:
- environment_slug: html
  github:
    branch: release
    deploy_on_push: true
    repo: 1fpga/golem.1fpga.cloud
  name: golem-1fpga-cloud
  source_dir: /
  output_dir: /dist
  build_command: npm install && npm run -w build build

