name = "Mister Chess Core"
uniqueName = "mister-chess"
description = "Mister FPGA Chess core"
systems = [ "other" ]
icon = "./chess-256.png"

[[releases]]
version = "20240410"
tags = [ "latest" ]

[[releases.files]]
type = "mister.core.rbf"
url = "./20240410/chess.rbf"
size = 0 # Updated by the build system.
sha1 = "" # Updated by the build system.
