name = "Mister Chess Core"
uniqueName = "mister-chess"
description = "Mister FPGA Chess core"
systems = [ "chess" ]

[[releases]]
version = "20240410"

[[releases.files]]
type = "mister.core.rbf"
url = "./20240410/chess.rbf"
size = 3711324
sha1 = "ff24e45b6c079facc4702c923c6ec9ea97e65444"
