db_id = "1fpga/1fpga"
db_url = "https://catalog.1fpga.cloud/db/db.json.zip"
timestamp = 1731953763

[files."Scripts/1fpga.sh"]
url = "https://catalog.1fpga.cloud/db/Scripts/1fpga.sh"
tags = [16]
hash = "" # Updated by the build system.
size = 0 # Updated by the build system.

[folders."Scripts"]
tags = [16]

[tag_dictionary]
scripts = 16
