name = "Mister Input Test"
uniqueName = "mister-inputtest"
description = "Input Test for the Mister FPGA"
systems = [ "utility" ]
tags = [ "no-roms" ]

[[releases]]
version = "20240727"
tags = [ "latest" ]

[[releases.files]]
type = "mister.core.rbf"
url = "./releases/mister-inputtest/20240727/inputtest.rbf"
size = 0 # Updated by the build system.
sha256 = "" # Updated by the build system.
