name = "Mister Chess"
gameName = "Chess"
uniqueName = "mister-chess"
description = "Mister FPGA Chess core"
systems = ["other"]
icon = "./chess-256.png"
tags = ["no-roms", "game"]

[[releases]]
version = "20240410"
tags = ["latest"]

[[releases.files]]
type = "mister.core.rbf"
url = "./releases/mister-chess/20240410/chess.rbf"
size = 0 # Updated by the build system.
sha256 = "" # Updated by the build system.
