[mister-nes]
name = "Nintendo Entertainment System"
system = "nes"
description = "Mister FPGA NES core"

[[mister-nes.releases]]
files = [
  "https://cloud.1fpga.com/cores/mister-nes/20230223/nes.rbf"
]
date = "2023-02-23"
