name = "NES"
uniqueName = "nes"
description = """\
    The Nintendo Entertainment System (NES) is an 8-bit home video game console\
    that was developed and manufactured by Nintendo.\
"""
tags = ["nes", "nintendo", "8-bit"]
category = "console"

# This is deprecated, but kept in case people use an older version.
# Remove this by 0.2.4.
[gamesDb]
version = "20241001"
url = "./nes/nes.json"
size = 0 # Updated by the build system.
sha256 = "" # Updated by the build system.

[db]
version = "20241001"
url = "./nes/nes.sqlite"
size = 0    # Updated by the build system.
sha256 = "" # Updated by the build system.
