name = "1FPGA"
version = "20241029"

[systems.nes]
url = "source/nes.json"
version = "20240920"

[systems.chess]
url = "source/chess.json"
version = "20240920"

[systems.flappy-bird]
url = "source/flappy-bird.json"
version = "20200402"

[systems.memtest]
url = "source/memtest.json"
version = "20210130"
