name = "1FPGA"
version = "20240920"
lastUpdated = "2024-09-20 00:00:00"

[systems.nes]
url = "source/nes.json"
version = "20240920"

[systems.chess]
url = "source/chess.json"
version = "20240920"

[systems.flappy-bird]
url = "source/flappy-bird.json"
version = "20200402"
