name = "Nintendo Entertainment System"
uniqueName = "mister-nes"
description = "Mister FPGA NES core"
systems = [ "nes" ]

[[releases]]
version = "20230223"
tags = [ "latest" ]

[[releases.files]]
type = "mister.core.rbf"
url = "./20230223/nes.rbf"
size = 3204048
sha1 = "cdef876281a9cffc30c58f9a1e41c11b92e992db"
