[mister-nes]
url = "./cores/mister-nes.json"
version = ""

[mister-chess]
url = "./cores/mister-chess.json"
version = ""

[mister-flappy-bird]
url = "./cores/mister-flappy-bird.json"
version = ""

[mister-arduboy]
url = "./cores/mister-arduboy.json"
version = ""

[mister-memtest]
url = "./cores/mister-memtest.json"
version = ""

[mister-inputtest]
url = "./cores/mister-inputtest.json"
version = ""
