[nes]
url = "./systems/nes.json"
db = "./systems/nes.catalog"
dbSize = 0 # Updated by the build system.
dbSha256 = "" # Updated by the build system.
version = ""

[other]
url = "./systems/other.json"
version = ""

[utility]
url = "./systems/utility.json"
version = ""
