name = "NES"
uniqueName = "nes"
description = """\
    The Nintendo Entertainment System (NES) is an 8-bit home video game console that was developed and \
    manufactured by Nintendo. It was initially released in Japan as the Family Computer Famirī Konpyūta) \
    (also known by the portmanteau abbreviation Famicom (Famikon) and abbreviated as FC) on July 15, 1983, \
    and was later released in North America during 1985, in Europe during 1986, and Australia in 1987.\
"""

# This should be updated semi-regularly.
[gamesDb]
version = "20240202"
url = "../dat/nes.json"
size = 1633145
sha1 = "e576f8641b5d3b3b832922fbb4c4cd8d9e1ccbcd"

[cores.mister-nes]
version = "20230223"
url = "../cores/mister-nes/mister-nes.json"
