name = "Other"
uniqueName = "other"
description = """\
    Any core that doesn't fit into the other categories.\
"""
tags = [ "other", "no-roms" ]
icon = "./other-256.png"

[cores.mister-chess]
version = "20240410"
url = "../cores/mister-chess/mister-chess.json"

[cores.mister-flappy-bird]
version = "20200402"
url = "../cores/mister-flappy-bird/flappy-bird.json"
